### ISSUE TITLE
Map collapse by default

### ISSUE THREAD

**Issue by Cloneill-2021** [earthwiseaware/field_surveys#20]
Have the map collapse by default as in the Survey123 version.

**Comment by mgietzmann** [comment]
I left it uncollapsed given the point is to allow the user to see what their location is set to and change it if needed. I figured if it was collapsed it'd be easy to forget to check and then not notice it's off. Plus the map doesn't even take up half of the screen.

**Comment by Cloneill-2021** [comment]
FYI: We ended up collapsing it in other surveys based on the feedback of users. I.e., regular users usually check it at the beginning of a field session, then once they're sure the GPS is correct for the first few records, they don't check it for the rest of the session. I have it still uncollapsed for one survey (happening at the Blue Hills) and they miss their previous collapsed map (I have a todo to get it back - there was a bug in the past) :D

**Comment by Cloneill-2021** [comment]
Yes, and that might be ok here (in our Buggy app), since there is no scroll just a move to the next tab/page [unless we get more things on that page :-D]

**Comment by mgietzmann** [comment]
Yea if we add more stuff to the page, I'll totally make it collapsible. :)
