### ISSUE TITLE
'other' option with text field.

### ISSUE THREAD

**Issue by Cloneill-2021** [earthwiseaware/field_surveys#21]
When 'other' choice is selected have an associated text field in in the Survey123 version. 
'Other' option shows in the following survey fields:
- Survey method
- Arthropod group
- Developmental stage
- Activity
- host taxonomic group
- phenology

**Comment by mgietzmann** [comment]
Fixed with https://github.com/earthwiseaware/field_surveys/commit/b7db95fe87337df8d2e56338107081191e387869
