### ISSUE TITLE
Date and time In first page/tab 

### ISSUE THREAD

**Issue by Cloneill-2021** [earthwiseaware/field_surveys#22]
Have 'date and time' filled automatically but showing by default in first page/tab of the survey just before the map

**Comment by mgietzmann** [comment]
Given one cannot change the value of date time (if using xlsform's auto date) there's no point in showing it (and by default that value is not shown - in fact I  don't know if you can show it).

**Comment by Cloneill-2021** [comment]
Hmmm. Weird that Survey Connect operates this way. Our other Survey123 surveys show it - and it's fine. 
It's also a common practice for such apps too:  Caterpillars Count, iNaturalist, Nature's Notebook, have the date and time showing (set by default and modifiable).

**Comment by mgietzmann** [comment]
I can look to see if there's a way to make it appear.

**Comment by Cloneill-2021** [comment]
Here on the  Survey123 version, in case you did not see it
![Screenshot_20220627-153802](https://user-images.githubusercontent.com/104395263/176022288-0d4e9ba5-17bb-4100-bac3-7a88dabea338.png) I am assuming there's a SurveyConnect equivalent (?)

**Comment by mgietzmann** [comment]
Fixed with https://github.com/earthwiseaware/field_surveys/commit/be5b766b898e0927a96cc3145ec543b095202a9c
