### ISSUE TITLE
Needs to collect the email

### ISSUE THREAD

**Issue by Cloneill-2021** [earthwiseaware/field_surveys#27]
Currently missing collecting surveyor's email. Important to be able to communicate errors, mis-indentification/mis-classification, etc.

**Comment by mgietzmann** [comment]
It does get collected automatically: https://github.com/earthwiseaware/field_surveys/blob/arthropods/arthropods/survey.json#L16

**Comment by Cloneill-2021** [comment]
Hmmm... I am not seeing it on the data side. Only mine shows, not from those who signed up anonymously (which is key): the volunteers don't have ESRI licenses.

**Comment by mgietzmann** [comment]
Yea they just need to sign into _an_ esri account. They don't need licenses from what I remember.

**Comment by Cloneill-2021** [comment]
So they need to create one? Hmmm...

**Comment by mgietzmann** [comment]
Yea I mean I can add a text box, but then there's no way for us to verify it's a real email, plus people can put in emails that aren't their own which leads to all kinds of issues if we want to start sending people stuff.

**Comment by Cloneill-2021** [comment]
Ok. I'll talk to Kate our tester to ask her to sign up for a free ESRI account.

**Comment by mgietzmann** [comment]
Sounds good.

**Comment by Cloneill-2021** [comment]
Hmmm... It happens that my phone died this morning, so I tried with an old phone. I tried to sign up using a public free account, and I was denied access to the survey.
![Screenshot_20220718-115659](https://user-images.githubusercontent.com/104395263/179553117-ccda8201-a23f-4cd7-ac39-91b9b6203721.png)

Am I doing something wrong, or does this means that Survey123 can't be used the way we intended.

**Comment by Cloneill-2021** [comment]
Yep.... It's insane, isn't it? See you a little later today :-)

Cheers! - Claire
Earthwise Aware <https://www.earthwiseaware.org/> | Executive Director
✉ ***@***.***
✆ +1 781-883-5970 | LinkedIn Profi <https://www.linkedin.com/in/coneill/>le
<https://www.earthwiseaware.org/>

<https://www.earthwiseaware.org/>

Nature Conservation as a Way Of Life

ⓘ *www.earthwiseaware.org <https://www.earthwiseaware.org>* | *EwA
Newsletter Signup » <https://eepurl.com/dl0mdD>*

🧡 Become an EwA #ScienceForAll Ambassador » *Donate
<https://www.paypal.com/donate?token=Yzw6GUsevRISYKwaJbfYLFuROgR--S6hYUi3MXy17zaRF2wzQFFJOdYXXvOFAyi-QPwNaBSfSTadFvI2>*

**Comment by mgietzmann** [comment]
Okay given that public users can't sign into survey123 at all, I'll add an email field and also capture the deviceID

**Comment by mgietzmann** [comment]
https://github.com/earthwiseaware/field_surveys/commit/4a5634e02fed6e46975f59115bddf79209bfa631

**Comment by Cloneill-2021** [comment]
The identifier text field for all our surveyors is: 

Field is required. The answer can be cached so that it can populate automatically.
Field title: Team member identifier
Description: Please enter your email so that we can contact you if we have a question regarding a record.

Note that surveys can't be anonymous, this is a citsci/science data standard.
