### ISSUE TITLE
hyperlink 

### ISSUE THREAD

**Issue by Cloneill-2021** [earthwiseaware/field_surveys#30]
There is a supposedly a way to add a hyperlink to a note in a form, but I haven't been successful at making it work 
Ref: https://community.kobotoolbox.org/t/i-would-like-to-add-a-hyperlink-to-a-question-is-it-possible-with-kobo/18542

I'd want to try that in the last note of our kobo buggy survey

**Comment by mgietzmann** [comment]
I can add a hyperlink just fine. The syntax is:
```
[the text you want to display](https://the.full.link/)
```
So for example if I want to direct people to Google I could do:
```
Click [here](https://www.google.com) to navigate to Google.
```

**Comment by Cloneill-2021** [comment]
Hmmm... I tried that syntax and it did not work for me. I am confused. Is
there a specific location in the xls where that goes? What am I missing?

**Comment by mgietzmann** [comment]
I just put it straight in the text. Perhaps it has to be in a note type question?

**Comment by Cloneill-2021** [comment]
I finally got is working.
