### ISSUE TITLE
Limiting the number of photo records in a survey

### ISSUE THREAD

**Issue by Cloneill-2021** [earthwiseaware/field_surveys#32]
There should be a way to restrict the number of photo records (Google forms allow that for sure, as well as ArcGIS if I am correct). I am not finding how to do it.

**Comment by mgietzmann** [comment]
https://xlsform.org/en/#fixed-repeat-counts

**Comment by Cloneill-2021** [comment]
I'll try that too :-)

**Comment by Cloneill-2021** [comment]
Hmmmm.... This one imposes a number of repeats. Can we impose an upper limit only. That is, not more than 3 pics for instance. 1 photo is ok, but not more than 3. I search for keywords s.s. 'max', or 'upper', or 'less'. But there must be sth though (Google forms have that feature  for instance).

**Comment by Cloneill-2021** [comment]
It needs to be a string, note a text, not a note... I got that in. I'll send the xls later.

**Comment by Cloneill-2021** [comment]
Never mind, it's not a fix... Or I'd have to fill with some text. Darn!

**Comment by mgietzmann** [comment]
See this section of the ODK documentation: https://docs.getodk.org/form-repeats/#using-relevants-to-limit-repetitions

Basically instead of using a repeat at all you can specify say 5 image questions in a row but use a condition to only make them viewable when the last image was input.
